

---
title: "Not all exposures are created equal"
author: "Kylie Ainslie, Nathalie Dean, Hein Putter, David Price, Fanny Bergström"
date: today
---

## Project Aim
In this project, we aim to improve the statistical efficiency of VE estimation by leveraging data on the estimated force of infection experienced by different subpopulations.
Consider subpopulations $k=1,\dots,K$. In mechanistic models, the force of infection experienced by subpopulation k is a function of the sum of the contact rates and numbers infected:

$$\lambda_k(t) = \sum_{j=1}^K c_{jk}I_j(t)$$

## Scientific Background

### Literature

- Moore *et al.* 2023 *Epidemics* doi: [https://doi.org/10.1016/j.epidem.2024.100768](https://doi.org/10.1016/j.epidem.2024.100768)

## Methods

\begin{align}
h(t, t_c) &= h_0(t, t_c)\exp(\gamma(t)V + \dots) \\
          &= h_0(t_c)\exp(\gamma(t)V + \dots) \\
          &= \gamma\bar{I}(t_c)\exp(\gamma(t)V + \dots)
          $= \exp(\gamma(t)V + \log(\beta\bar{I}(t_c)) + \dots)

\end{align}

where $t$ is calendar time, $t_c$ is calendar time, $\bar{I}$ is a function of infectiousness in the population. 

$$\beta\bar{I}(t_c) = \beta\sum_a'\left(I_u^{a'}(t_c-1) + (1-\theta(t))I_v^{a'}(t-1) \right) \frac{C_{a'a}}{N_a} $$
where $a'$ indexes age groups, and $a$ indexes subgroups within those age groups. The term $C_{a'a}$ represents the contact matrix between age group $a'$ and subgroup $a$, and $N_a$ is the population size of subgroup $a$. 

## Data

### Data Needs

- time of vaccination
- time of infection
- age
- contact patterns (external)
- relative infectiousness of vaccinated people
- background incidence from pop

## Analysis

1. Artificially create a cohort
2. Calculate  background population parameters (e.g., incidence)

## Results

## Discussion and Limitations

## Session Info

```{r}
sessionInfo()
```

